"""Initial migration

Revision ID: 051ffb4a5637
Revises: 
Create Date: 2025-01-13 13:52:11.966650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '051ffb4a5637'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('option', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_correct', sa.Boolean(), nullable=True))

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('correct_option_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'option', ['correct_option_id'], ['id'])
        batch_op.alter_column('correct_option_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('option', schema=None) as batch_op:
        batch_op.drop_column('is_correct')

    # ### end Alembic commands ###
